### ISSUE TITLE
Issue in null-ls health and mason check

### ISSUE THREAD

**Issue by BharathLakkoju** [slydragonn/dotfiles#1]
![image](https://user-images.githubusercontent.com/73902405/222904555-b7889311-6ea0-4546-848a-24180ec3b297.png)
![image](https://user-images.githubusercontent.com/73902405/222904658-813d0c01-b4a9-4f07-ae84-e79579f64eea.png)
These are the errors I've been getting every time I run  nvim command or open any file using nvim command
and I am using windows system so please tell me what are the key bindings. All I can see was <leader> term which I don't know how to use.

**Comment by slydragonn** [comment]
Hi @BharathLakkoju, thanks for reporting this issue.

The mason-lspconfig error, I recently fixed this error on the code. This error was caused why by the lsp.lua file missing some server setups, as you can see:
![lspconfig](https://user-images.githubusercontent.com/86858494/222925603-b9e48267-f0c4-40e0-919f-588e58d7b253.png)

You can update the code and run the command `:PackerSync`, I recommend that you run this command two times and make sure that all is installed correctly.

For the error with null-ls, this error is caused by why the linters don't install automatically when the neovim config is installing, for this, you should install the linters manually with `:MasonInstall` command and make sure that they are installed with the command `:Mason` and see the state of the plugins.

Try running this command to install the missing linters:

`:MasonInstall prettier prettierd eslint_d shellcheck pylint`

**Note:** For `rustfmt` and `stylua` make sure you have installed rust and lua with their respective package managers on your PC.

When the installation is ready run the command `:checkhealth` and you should see this:
![null-lsp](https://user-images.githubusercontent.com/86858494/222925590-5a19159b-2182-4252-a0bb-38c891bcdd69.png)

**Comment by slydragonn** [comment]
### For the keybindings question, are the following:

**`<leader>` = `the space key`**

- Quit = `space + q`
- Save = `space + w`
- Exit Insert mode = `j + k`
- Horizontal window = `space + p`
- Vertical window = `space + ñ`
- Open file manager = `space + e`
- Focus on file manage = `space + 0`
- Buffer
	- next buffer = `the tab key`
	- previous buffer = `shift + tab`
- Open terminal = `F7`
- Horizontal terminal = `space + t + h`
- Vertical terminal = `space + t + v`
- Windows navigation
	- move left = `control + h`
	- move right = `control + l`
	- move up = `control + k`
	- move down = `control + j`
- Resize Windows
	- More vertical = `control + right key`
	- Less vertical = `control + left key`
	- More horizontal = `control + up key`
	- Less horizontal = `control + down key`
- Telescope
	- find files = `space + f + f`
	- find words = `space + f + g`
	- show buffers = `space + f + b`
	- help = `space + f + h`
	- show git status = `space + f + s`
	- show git commits = `space + f + c`

**Comment by BharathLakkoju** [comment]
![image](https://user-images.githubusercontent.com/73902405/222962754-cf0bc12a-b30a-45a2-9ba8-a66ef3e50ab7.png)
This is working for **python**.
![image](https://user-images.githubusercontent.com/73902405/222962873-2516dab9-38fa-4332-8cbf-a24eb2ce8f7e.png)
Not for any other languages
and why is it system32/cmd. PATH for python and not for others.
all other languages are in my path itself.
for better understanding -->
![image](https://user-images.githubusercontent.com/73902405/222963026-dd88df00-deca-4076-a7d4-0690f0c3d864.png)

**Comment by slydragonn** [comment]
To add language support, you should write inside lsp.lua file, the next snippet to enable the language server. For the Java case, the snippet is the following.

```lua
-- ~/configs/lsp.lua

-- Java server
nvim_lsp.java_language_server.setup{}
```

More info about how to enable a new language:
- nvim-lspconfig repository: https://github.com/neovim/nvim-lspconfig
- Config for Java: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#java_language_server
- Support Languages List: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md

**Comment by saihanhtet** [comment]
![image](https://user-images.githubusercontent.com/111681901/225526043-703ee49a-5545-4edb-91e5-2e41aed585f0.png)
i am having trouble with the nvim-treesitter can you help?

**Comment by slydragonn** [comment]
Hi @saihanhtet, that error may be because you don't have the C compiler installed, so first install the compiler on your pc according to the operating system and then run the command to install the neovim plugins.

Here are a couple of resources from the [nvim-treesitter](https://github.com/nvim-treesitter) community to install the C compiler:
* Windows: https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support#gcc
* Linux: https://github.com/nvim-treesitter/nvim-treesitter/wiki/Linux-Support

**Comment by saihanhtet** [comment]
Thank you Sir. I install the c compiler as you said and now it is work. ❤️ Sent from Mail for Windows From: Alejandro LondoñoSent: Friday, March 17, 2023 7:25 AMTo: slydragonn/dotfilesCc: SaiHanHtet; MentionSubject: Re: [slydragonn/dotfiles] Issue in null-ls health and mason check (Issue #1) Hi @saihanhtet, that error may be because you don't have the C compiler installed, so first install the compiler on your pc according to the operating system and then run the command to install the neovim plugins.Here are a couple of resources from the nvim-treesitter community to install the C compiler:Windows: https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support#gccLinux: https://github.com/nvim-treesitter/nvim-treesitter/wiki/Linux-Support—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
